def song(adjective1, adjective2 ,adjective3, pluralnoun1, pluralnoun2, pluralnoun3, noun1, noun2, noun3, phrase1):
    print("\n\n")
    print(f"Six {adjective1} {pluralnoun1} sit in the {noun1}.")
    print(f"Do they fit?")
    print()
    print(f"Six {adjective2} {pluralnoun2} sit in the {noun2}.")
    print(f"Do they fit?")
    print()
    print(f"Six {adjective3} {pluralnoun3} sit in the {noun3}.")
    print(f"Do they fit?")
    print()
    print(f"Sit. Fit? {phrase1}")

input_adjective1 = input("Enter an adjective: ")
input_adjective2 = input("Enter another adjective: ")
input_adjective3 = input("Enter another adjective: ")
input_pluralnoun1 = input("Enter a plural noun: ")
input_pluralnoun2 = input("Enter another plural noun: ")
input_pluralnoun3 = input("Enter another plural noun: ")
input_singularnoun1 = input("Enter a singular noun:")
input_singularnoun2 = input("Enter another singular noun:")
input_singularnoun3 = input ("Enter another singualr noun:")
input_exclamation_phrase = input("Enter a exclamation phrase (Yes!, Are you Kidding?): ")
song (input_adjective1, input_adjective2, input_adjective3, input_pluralnoun1, input_pluralnoun2, input_pluralnoun3, input_singularnoun1, input_singularnoun2, input_singularnoun3, input_exclamation_phrase )
